# Generated by Django 4.1.5 on 2023-01-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=80)),
                ("Author", models.CharField(max_length=40)),
                ("Isbn", models.CharField(max_length=20)),
                ("Publisher", models.CharField(max_length=50)),
            ],
            options={"db_table": "book",},
        ),
    ]
